extends:
  - "@commitlint/config-conventional"
parserPreset: "conventional-changelog-conventionalcommits"
rules:
  type-empty:
    - 2
    - "never"
  type-case:
    - 2
    - "always"
    - "lower-case"
  type-enum:
    - 2
    - "always"
    - [
        "build",
        "chore",
        "ci",
        "docs",
        "feat",
        "fix",
        "perf",
        "refactor",
        "revert",
        "style",
        "test",
        "types"
      ]
  subject-empty:
    - 2
    - "never"
  subject-case:
    - 2
    - "never"
    - ["sentence-case", "start-case", "pascal-case", "upper-case"]
  subject-full-stop:
    - 2
    - "never"
    - "."
  body-leading-blank:
    - 2
    - "always"
  header-max-length:
    - 2
    - "always"
    - 100
  footer-leading-blank:
    - 1
    - "always"
  footer-max-line-length:
    - 2
    - "always"
    - 100
prompt:
  questions:
    type:
      description: "Select the type of change that you're committing"
      enum:
        feat:
          description: "A new feature"
          title: "Features"
          emoji: "✨"
        fix:
          description: "A bug fix"
          title: "Bug Fixes"
          emoji: "🐛"
        docs:
          description: "Documentation only changes"
          title: "Documentation"
          emoji: "📚"
        style:
          description: "Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)"
          title: "Styles"
          emoji: "💎"
        refactor:
          description: "A code change that neither fixes a bug nor adds a feature"
          title: "Code Refactoring"
          emoji: "📦"
        perf:
          description: "A code change that improves performance"
          title: "Performance Improvements"
          emoji: "🚀"
        test:
          description: "Adding missing tests or correcting existing tests"
          title: "Tests"
          emoji: "🚨"
        build:
          description: "Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)"
          title: "Builds"
          emoji: "🛠"
        ci:
          description: "Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)"
          title: "Continuous Integrations"
          emoji: "⚙️"
        chore:
          description: "Other changes that don't modify src or test files"
          title: "Chores"
          emoji: "♻️"
        revert:
          description: "Reverts a previous commit"
          title: "Reverts"
          emoji: "🗑"
        types:
          description: "Type definition file changes"
          title: "Types"
          emoji: "🌟"
