"*.{json,md,yml}":
  - prettier --write
"**/*.js?(x)":
  - "eslint --fix"
  - "prettier --write"
"**/*.ts?(x)":
  - "eslint --fix"
  - "prettier --write"
"{!(package)*.json,*.code-snippets,.!(browserslist)*rc}":
  - "prettier --write--parser json"
